object Versions {
    const val kotlinVersion = "1.8.0"
    const val roomVersion = "2.5.1"
    const val composeVersion = "1.5.0-alpha01"
    const val composeLifecycle = "2.6.0-alpha01"
    const val navigationVersion = "2.4.0"
    const val appCompatVersion = "1.4.0"
    const val coroutinesVersion = "1.5.2"
    const val dataStoreVersion = "1.1.0-dev01"
    const val viewModelVersion = "2.5.1"
    const val materialVersion = "1.1.1"
    const val hiltVersion = "2.46.1"
    const val timberVersion = "4.7.1"
    const val coreVersion = "1.7.0"
    const val composeConstraint = "1.0.0"
    const val composeNavigation = "2.5.0-alpha01"
    const val navigationComposeAnimation = "0.28.0"
    const val composeRuntime = "1.2.0-alpha04"
    const val accompanistVersion = "0.24.1-alpha"
    const val accompanistInsetsVersion = "0.24.3-alpha"
    const val accompanistUiControllerVersion = "0.27.0"
    const val coilVersion = "1.4.0"
    const val jodaTimeVersion = "2.10.13"
    const val moshiVersion = "1.13.0"
    const val composeHiltNavVersion = "1.0.0"
    const val landscapistVersion = "2.1.0"
    const val landscapistCoilVersion = "2.1.0"
}